version: '3.9'
services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: dtf
      POSTGRES_PASSWORD: dtf
      POSTGRES_DB: dtf
    ports:
      - "5432:5432"
    volumes:
      - dtf_postgres:/var/lib/postgresql/data
volumes:
  dtf_postgres:
